import express from 'express';

const router = express.Router();
const { authenticate } = require('../middlewares/authMiddleware');
const HospedagemAdminController = require('../controllers/HospedagemAdminController');

// Endpoints oficiais
router.get(
    '/hospedagem/refresh-version',
    authenticate,
    HospedagemAdminController.refreshVersion
);
router.get(
    '/hospedagem/reservas',
    authenticate,
    HospedagemAdminController.listarReservas
);
router.get(
    '/hospedagem/reservas/:id',
    authenticate,
    HospedagemAdminController.detalheReserva
);
router.post(
    '/hospedagem/reservas/:id/checkin',
    authenticate,
    HospedagemAdminController.realizarCheckin
);
router.post(
    '/hospedagem/reservas/:id/registrar-chegada',
    authenticate,
    HospedagemAdminController.registrarChegada
);
router.post(
    '/hospedagem/reservas/:id/checkout',
    authenticate,
    HospedagemAdminController.realizarCheckout
);
router.post(
    '/hospedagem/reservas/:id/cancelar',
    authenticate,
    HospedagemAdminController.cancelarReserva
);
router.post(
    '/hospedagem/reservas/recepcao',
    authenticate,
    HospedagemAdminController.criarReservaRecepcao
);
// Enviar reserva para o cliente finalizar (novo — não altera /recepcao)
router.post(
    '/hospedagem/reservas/recepcao/enviar-cliente',
    authenticate,
    HospedagemAdminController.enviarReservaParaCliente
);
router.post(
    '/hospedagem/reservas/:id/reenviar-link',
    authenticate,
    HospedagemAdminController.reenviarLinkPagamento
);
router.get(
    '/hospedagem/reservas/:id/suites-disponiveis-troca',
    authenticate,
    HospedagemAdminController.listarSuitesDisponiveisTroca
);
router.post(
    '/hospedagem/reservas/:id/trocar-suite',
    authenticate,
    HospedagemAdminController.trocarSuite
);
router.post(
    '/hospedagem/reservas/:id/alterar-periodo',
    authenticate,
    HospedagemAdminController.alterarPeriodo
);
router.patch(
     '/hospedagem/reservas/:id/usuario',
     authenticate,
     HospedagemAdminController.atualizarUsuarioReserva
 );


// Alias legado (mesma lógica)
router.get(
    '/hospedagem-admin/refresh-version',
    authenticate,
    HospedagemAdminController.refreshVersion
);
router.get(
    '/hospedagem-admin/reservas',
    authenticate,
    HospedagemAdminController.listarReservas
);
router.get(
    '/hospedagem-admin/reservas/:id',
    authenticate,
    HospedagemAdminController.detalheReserva
);
router.post(
    '/hospedagem-admin/reservas/:id/checkin',
    authenticate,
    HospedagemAdminController.realizarCheckin
);
router.post(
    '/hospedagem-admin/reservas/:id/registrar-chegada',
    authenticate,
    HospedagemAdminController.registrarChegada
);
router.post(
    '/hospedagem-admin/reservas/:id/checkout',
    authenticate,
    HospedagemAdminController.realizarCheckout
);
router.post(
    '/hospedagem-admin/reservas/:id/cancelar',
    authenticate,
    HospedagemAdminController.cancelarReserva
);
router.post(
    '/hospedagem-admin/reservas/recepcao',
    authenticate,
    HospedagemAdminController.criarReservaRecepcao
);
router.post(
    '/hospedagem-admin/reservas/recepcao/enviar-cliente',
    authenticate,
    HospedagemAdminController.enviarReservaParaCliente
);
router.post(
    '/hospedagem-admin/reservas/:id/reenviar-link',
    authenticate,
    HospedagemAdminController.reenviarLinkPagamento
);
router.get(
    '/hospedagem-admin/reservas/:id/suites-disponiveis-troca',
    authenticate,
    HospedagemAdminController.listarSuitesDisponiveisTroca
);
router.post(
    '/hospedagem-admin/reservas/:id/trocar-suite',
    authenticate,
    HospedagemAdminController.trocarSuite
);
router.post(
    '/hospedagem-admin/reservas/:id/alterar-periodo',
    authenticate,
    HospedagemAdminController.alterarPeriodo
);
router.patch(
    '/hospedagem-admin/reservas/:id/observacoes',
    authenticate,
    HospedagemAdminController.atualizarObservacoes
);
router.get(
    '/hospedagem-admin/suites',
    authenticate,
    HospedagemAdminController.listarSuites
);
router.get(
    '/hospedagem-admin/suites/:id',
    authenticate,
    HospedagemAdminController.detalheSuite
);
router.get(
    '/hospedagem/suites',
    authenticate,
    HospedagemAdminController.listarSuites
);
router.get(
    '/hospedagem/suites/:id',
    authenticate,
    HospedagemAdminController.detalheSuite
);

module.exports = router;
