-- DEPRECATED / SUPERSEDED
-- Este script antigo convertia CLIENTE → SITE e forçava ENUM('SITE','ATENDENTE'),
-- o que é INCOMPATÍVEL com dados de produção (CLIENTE | ATENDENTE).
--
-- NÃO execute as etapas destrutivas abaixo em produção.
-- Use em vez disso: alter-hospedagem-origem-varchar.sql
--
-- (Mantido apenas como histórico / referência.)

-- --- NÃO EXECUTAR EM PRODUÇÃO ---
-- ALTER TABLE ReservaHospedagem
--   MODIFY COLUMN origemReserva VARCHAR(20) NOT NULL DEFAULT 'SITE';
--
-- UPDATE ReservaHospedagem
-- SET origemReserva = 'SITE'
-- WHERE origemReserva IS NULL
--    OR origemReserva = ''
--    OR origemReserva = 'CLIENTE';
--
-- ALTER TABLE ReservaHospedagem
--   MODIFY COLUMN origemReserva ENUM('SITE', 'ATENDENTE') NOT NULL DEFAULT 'SITE';
-- --- FIM NÃO EXECUTAR ---

-- Adição de idUsuarioCriacao (segura se a coluna ainda não existir):
-- ALTER TABLE ReservaHospedagem
--   ADD COLUMN idUsuarioCriacao INT NULL AFTER origemReserva;
